version: "3"

services:
  n1kko777devbot:
    container_name: n1kko777devbot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped

  nginx:
    build: ./nginx
    restart: always
    container_name: n1kko777devbot-nginx
    env_file: .env
    environment:
      - VIRTUAL_HOST=${URL}
      - LETSENCRYPT_HOST=${URL}
      - LETSENCRYPT_EMAIL=${EMAIL_HOST_USER}
    depends_on:
      - n1kko777devbot

networks:
  default:
    external:
      name: proxy-bypass
